import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { createCensor } from '../src/index.js';
import { inventedCensor } from './helpers.js';

const overlay = createCensor({ replaceCatalog: true });
const full = createCensor();

function assertAllow(censor, prompt, label) {
  const result = censor.check(prompt);
  assert.equal(
    result.verdict,
    'allow',
    `${label} ${JSON.stringify(prompt)} => ${result.verdict} (${result.reasons.join('; ')}) spans=${JSON.stringify(result.spans.map((span) => span.text))}`,
  );
}

describe('allow-path / innocent usage', () => {
  const vibePrompts = [
    'warm tape lo-fi drums',
    'jangly guitar take',
    'bar-room guitar',
    'synth stab',
    'late-night keys',
    'soft tape vocal',
    'cheap speakers bounce',
    'analog bus stacked chorus',
    'dusty cassette, no crowd noise',
    'melancholic jazz piano, intimate vocal air',
    'tape-saturated folk stomp',
    'dusty vinyl crackle bed',
    'cathedral reverb tail',
    'muted trumpet air',
    'slowed trap bounce',
    'detuned choir swells',
    'phaser-heavy psych groove',
    'fingerpicked nylon intro',
    'sub-bass pulse under soft keys',
    'rainy rhodes, room tone',
    'glockenspiel sparkle, gentle strum',
    'flute loop with chopped choir',
    'slow strings swell, no vocal',
    'chorused twelve-string shimmer',
  ];

  const directionPrompts = [
    'make it dreamier',
    'more 80s reverb',
    'less harsh highs',
    'film grain',
    'cinematic pads',
    'dreamy 80s synthwave, warm analog pads',
    'slower build into the chorus',
    'strip it back to piano',
    'add vinyl crackle and hiss',
    'more room tone, less polish',
    'brighter master, tame the mud',
    'easy feel on the bridge',
    'switch to a minor key midway',
    'make the drums switch up halfway',
    'push the tempo to 128',
    'drier vocal, wider pads',
  ];

  const objectPrompts = [
    'add a faint grenade thud under the kick',
    'toss a grenade into the foley bed',
    'kryptonite green lighting on the pad',
    'morning dew on the grass, field recording',
    'iris of the camera, slow zoom',
    'a wonderwall of stacked pads',
    'rain on me from the ceiling mics',
    'dont rain on me with extra reverb',
    'a sign of the times in the mix',
    '7 rings of reverb around the snare',
    'orbiter drone, slow sweep',
    'midnight sun through the window mics',
    'drop dead gorgeous vocal air',
    'be her friend on the chorus stack',
    'boston rain on the window mics',
    'leftover boston chowder in the green room',
    'a boston fern in the corner of the set',
    'dracula cape in the costume rack',
    'paper dracula teeth for the halloween sting',
    'nine to five shift whistle foley',
    'clocking nine to five warehouse ambience',
    'flip the pickup switch, second take',
    'a faulty light switch buzzing onsite',
    'something to lose, restless piano at midnight',
    'steamboat whistle foley with willie on harmonica',
    'a direct cinema cut, no captions',
    'forty hours of overtime, tired vocal take',
    'a thor cape prop on the workbench',
    'coco powder on the workbench, baking foley',
    'halo light rig, soft studio glow',
    'turned inside out, room tone',
    'toy storybook hour with kids, warm room',
    'the last of us left the room, quiet vocal',
    'boston cream donut in the green room',
    'boston terrier bark foley',
    'dracula parrot in the aviary ambience',
    'railroad switch yard ambience at dawn',
    'network switch hum in the server room',
    'nine-to-five traffic hum outside the booth',
    'grenadine syrup pour foley',
    'iris scanner beep foley',
    'a wall of canyon wonder reverb',
    'orbit decay drone swell',
    'loser bracket pinball foley at the arcade',
    'tired and jaded warehouse vocal at midnight',
    'farm animal foley, barn ambience',
    'her earrings clinked in the vocal booth',
    'the cure for the amp hum is less gain',
    'what you need is more room tone',
    'cinderella carriage prop on the set',
    'one piece of tape on the mic stand',
    'jolene nametag on the desk drawer',
    'oh yeah, push the fader up',
    'mid-atlantic ridge hydrophone foley',
    'universal reverb preset, large hall',
    'warner rainstorm field recording',
    'kindle a fire, field recording',
    'humanoid android costume prop on the set',
    'android phone foley, warm mics',
    'mail foley, warm mics',
    'dj set foley, warm mics',
    'sonar ping foley, warm mics',
    'canvas foley, warm mics',
    'canvas tote foley, warm mics',
    'when foley, warm mics',
    'quill foley, warm mics',
    'siri foley, warm mics',
    'kling foley, warm mics',
    'gorilla enclosure foley, warm mics',
    'play the station break foley',
    'barbecue smoke ambience, grill foley',
    'barbed fence wire foley, high wind',
    'blue tarp flapping foley, high wind',
    'fender bender foley, parking lot ambience',
    'muddy fender rattle foley, garage bed',
    'gibson desert foley, warm mics',
    'gibson guitar foley, warm mics',
    'coconut melon foley, warm mics',
    'fan art foley, warm mics',
    'open connection foley, warm mics',
    'instant gram foley, warm mics',
    'face book foley, warm mics',
    'prime rib foley, warm mics',
    'prime video essay foley, warm mics',
    'stable diffusion foley, warm mics',
    'deli foley bed, warm mics',
    'funky foley bed, warm mics',
    'matte finish foley, warm mics',
    'peso exchange rate foley, warm mics',
    'pluma feather foley, warm mics',
    'valor foley, warm mics',
    'hula dance foley, warm mics',
    'crunchy granola foley, warm mics',
    'read it later foley, warm mics',
    'yamaha foley, warm mics',
    'able foley, warm mics',
    'nerf the bass foley, warm mics',
    'hash brown foley, warm mics',
    'co-pilot foley, warm mics',
    'copilot foley, warm mics',
    'rock foley, warm mics',
    'eleven labs foley, warm mics',
    'cap cut foley, warm mics',
    'serrated knife foley, warm mics',
    'steamy vocal booth foley, warm mics',
    'sheen product shot foley, warm mics',
    'bose foley, warm mics',
    'idea foley, warm mics',
    'community unity foley, warm mics',
    'unity foley, warm mics',
    'perplexity foley, warm mics',
    'deep seek foley, warm mics',
    'pika foley, warm mics',
    'luma foley, warm mics',
    'lumen foley, warm mics',
    'wicked weather foley, warm mics',
    'hell diver foley, warm mics',
    'pal world foley, warm mics',
    'feud foley, warm mics',
    'hosier foley, warm mics',
    'cozier foley, warm mics',
    'wonky foley, warm mics',
    'wonk foley, warm mics',
    'backrooms foley, warm mics',
    'backroom foley, warm mics',
    'silk foley, warm mics',
    'silkworm foley, warm mics',
    'thunderbolts foley, warm mics',
    'thunderbolt foley, warm mics',
    'mandolin foley, warm mics',
    'mandala foley, warm mics',
    'grog foley, warm mics',
    'grove foley, warm mics',
    'air foley, warm mics',
    'air bed foley, warm mics',
    'door foley, warm mics',
    'dash foley, warm mics',
    'shop foley, warm mics',
    'shopfront foley, warm mics',
    'etude foley, warm mics',
    'fig foley, warm mics',
    'band foley, warm mics',
    'bonsai foley, warm mics',
    'patron foley, warm mics',
    'pattern foley, warm mics',
    'smokestack foley, warm mics',
    'jessie foley, warm mics',
    'murph foley, warm mics',
    'fife loop foley, warm mics',
    'only fans foley, warm mics',
    'fan foley, warm mics',
    'hey gen foley, warm mics',
    'venom foley, warm mics',
    'wall art foley, warm mics',
    'tech foley, warm mics',
    'chip foley, warm mics',
    'expedite foley, warm mics',
    'cost foley, warm mics',
    'insta foley, warm mics',
    'cart foley, warm mics',
    'script foley, warm mics',
    'describe foley, warm mics',
    'nut foley, warm mics',
    'intercom foley, warm mics',
    'billy foley, warm mics',
    'sierra nevada foley, warm mics',
    'feral cat foley, warm mics',
    'hollis hall foley, warm mics',
    'group vocal foley, warm mics',
    'frontier foley, warm mics',
    'delta blues foley, warm mics',
    'rune stone foley, warm mics',
    'under foley, warm mics',
    'tale foley, warm mics',
    'tales foley, warm mics',
    'dota foley, warm mics',
    'dot foley, warm mics',
    'gta foley, warm mics',
    'gt foley, warm mics',
    'castle foley, warm mics',
    'vania foley, warm mics',
    'zoo foley, warm mics',
    'utopia foley, warm mics',
    'gem foley, warm mics',
    'mini foley, warm mics',
    'manual foley, warm mics',
    'manta ray foley, warm mics',
    'idea gram foley, warm mics',
    'gram foley, warm mics',
    'kai foley, warm mics',
    'croc foley, warm mics',
    'clog foley, warm mics',
    'sierra foley, warm mics',
    'frontera foley, warm mics',
    'glaive foley, warm mics',
    'dandy lion foley, warm mics',
    'world foley, warm mics',
    'uma foley, warm mics',
    'musume foley, warm mics',
    'malilla foley, warm mics',
    'el foley, warm mics',
    'frag foley, warm mics',
    'punk foley, warm mics',
    'horse girl foley, warm mics',
    'teenage foley, warm mics',
    'engineering foley, warm mics',
    'rca foley, warm mics',
    'records foley, warm mics',
    'sam sung foley, warm mics',
    'sung foley, warm mics',
    'samson foley, warm mics',
    'synth foley, warm mics',
    'stuss foley, warm mics',
    'sussy foley, warm mics',
    'balen foley, warm mics',
    'ciaga foley, warm mics',
    'kreal foley, warm mics',
    'rea foley, warm mics',
    'd4 foley, warm mics',
    'nett foley, warm mics',
    'spend foley, warm mics',
    'mid foley, warm mics',
    'wxst foley, warm mics',
    'gquu foley, warm mics',
    'quux foley, warm mics',
    'dandys foley, warm mics',
    'op1 foley, warm mics',
    'quann foley, warm mics',
    'annic foley, warm mics',
    'shalli foley, warm mics',
    'popi foley, warm mics',
    'boynext foley, warm mics',
    'extdoor foley, warm mics',
    'qwe foley, warm mics',
    'wer foley, warm mics',
    'seyi foley, warm mics',
    'vibez foley, warm mics',
    'mega foley, warm mics',
    'bonk foley, warm mics',
    'adopt me foley, warm mics',
    'adopt foley, warm mics',
    'brook foley, warm mics',
    'haven foley, warm mics',
    'italian brainrot foley, warm mics',
    'italian foley, warm mics',
    'brainrot foley, warm mics',
    'rekord foley, warm mics',
    'box foley, warm mics',
    'capitol records foley, warm mics',
    'capitol foley, warm mics',
    'epic records session foley, warm mics',
    'epic foley, warm mics',
    'hyb foley, warm mics',
    'ybe foley, warm mics',
    'vig foley, warm mics',
    'ggle foley, warm mics',
    'higgs foley, warm mics',
    'field foley, warm mics',
    'corte foley, warm mics',
    'teiz foley, warm mics',
  ];

  const nearMissPrompts = [
    'go-go boots rhythm',
    'pistol snare crack',
    'baby bounce on cheap speakers',
    'miami night pads',
    'combs through the mix',
    'tems? wait no, tempos',
    'jude line the vocal booth with foam',
    'rusty bowstring fiddle texture',
    'enjoy conga breakdowns',
    'joyful conga layer under the hook',
    'vintage mason jar on the piano',
    'dolly in slowly, then part the curtains',
    'switch grass rustling, dry field mic',
    'a direct feed from the desk',
    'steam heat on the brass mic',
    'boss tone stack, crunch channel',
    'second switchback trail ambience',
    'how to lose the hum in the amp',
    'a moaning wind outside, night air',
    'spotty wifi foley, lo-fi bed',
    'a hobo campfire scene, warm grain',
    'sumo drums foley, taiko hit',
    'audio foley bed, room tone',
    'day by day field recording, slow build',
    'universal remote on the desk foley',
    'legacy console hum in the live room',
    'somber drone swell, dark pads',
    'my phone buzzes on the desk foley',
    'x box mic crate, roadie foley',
    'ps 5 mic positions, drum overheads',
    'street-pop mural on the brick wall',
    'shabby vocal booth foley, warm mics',
    'narrow hallway reverb foley',
    'chatty green room foley, warm mics',
    'mid journey field recording, slow build',
    'django guitar foley, warm mics',
    'grock foley, warm mics',
    'redder foley, warm mics',
    'crunchy roll foley, warm mics',
    'able tone foley, warm mics',
    'jlb foley, warm mics',
    'sham foley, warm mics',
    'pica foley, warm mics',
    'lumia foley, warm mics',
    'feuding vocal booth foley, warm mics',
    'boss pedal foley, warm mics',
    'latte art foley, warm mics',
    'open timer foley, warm mics',
    'salty air foley, warm mics',
    'burnt toast foley, warm mics',
    'cling wrap foley, warm mics',
    'kindling foley, warm mics',
    'sirius star field recording',
    'leo foley, warm mics',
    'veil foley, warm mics',
    'veo foley, warm mics',
    'hosier foley, warm mics',
    'wonky foley, warm mics',
    'silkworm foley, warm mics',
    'mandolin foley, warm mics',
    'grog foley, warm mics',
    'fig foley, warm mics',
    'etude foley, warm mics',
    'patron foley, warm mics',
    'smokestack foley, warm mics',
    'jess foley, warm mics',
    'mits foley, warm mics',
    'wetmore rain foley, warm mics',
    'batz foley, warm mics',
    'gabito foley, warm mics',
    'ballesteros rain foley, warm mics',
    'gelion foley, warm mics',
    'pub g foley, warm mics',
    'smisk foley, warm mics',
    'borg foley, warm mics',
    'heiser foley, warm mics',
    'rite foley, warm mics',
    'dj foley, warm mics',
    'lt foley, warm mics',
    'a spa day foley, warm mics',
    'spunky foley, warm mics',
    'near foley, warm mics',
    'sure foley, warm mics',
    'shore foley, warm mics',
    'ack foley, warm mics',
    'arthur foley, warm mics',
    'my lab bench foley, warm mics',
    'house band foley, warm mics',
    'distro kid foley, warm mics',
    'legato foley, warm mics',
    'gato foley, warm mics',
    'he rode his bike to the store',
    'road foley, warm mics',
    'misty morning foley, warm mics',
    'tucker bag foley, warm mics',
    'bratz foley, warm mics',
    'evangel choir foley, warm mics',
    'pub quiz foley, warm mics',
    'ski mask foley, warm mics',
    'corgi bark foley, warm mics',
    'senior foley, warm mics',
    'focus foley, warm mics',
    'pioneer foley, warm mics',
    'tax foley, warm mics',
    'skims foley, warm mics',
    'skimmer foley, warm mics',
    'rhode island foley, warm mics',
    'rhodes piano foley, warm mics',
    'motel foley, warm mics',
    'town foley, warm mics',
    'bill foley, warm mics',
    'delta foley, warm mics',
    'undertow foley, warm mics',
    'glave foley, warm mics',
    'glaives foley, warm mics',
    'davd foley, warm mics',
    'netspend foley, warm mics',
    'midwest foley, warm mics',
    'malila foley, warm mics',
    'el mal foley, warm mics',
    'frag pump foley, warm mics',
    'izzy foley, warm mics',
    'igna foley, warm mics',
    'qwerty foley, warm mics',
    'wert foley, warm mics',
    'boy door foley, warm mics',
    'nextdoor foley, warm mics',
    'stussey foley, warm mics',
    'valenciaga foley, warm mics',
    'samsong foley, warm mics',
    'synthesizer foley, warm mics',
    'rca cable foley, warm mics',
    'quan foley, warm mics',
    'shalom foley, warm mics',
    'poppy foley, warm mics',
    'boy text door foley, warm mics',
    'query foley, warm mics',
    'sexy foley, warm mics',
    'vibes foley, warm mics',
    'seyi vibes foley, warm mics',
    'megaphone foley, warm mics',
    'honk foley, warm mics',
    'adopt a highway foley, warm mics',
    'brook trout foley, warm mics',
    'haven house foley, warm mics',
    'italy foley, warm mics',
    'brain foley, warm mics',
    'rot foley, warm mics',
    'record foley, warm mics',
    'capital foley, warm mics',
    'epic fail foley, warm mics',
    'hype foley, warm mics',
    'hive foley, warm mics',
    'wiggle foley, warm mics',
    'jiggle foley, warm mics',
    'hugs foley, warm mics',
    'cortez foley, warm mics',
    'cortex foley, warm mics',
  ];

  // Overlaps that stay allow on the extras overlay but trip pre-existing
  // single-word entries in the shipped catalog (e.g. "One Piece", "God",
  // "Dawn Chorus") — asserted overlay-only by design.
  const overlayOnlyPrompts = [
    'god of warbler dawn chorus, field recording',
  ];

  it('keeps genre / vibe / production prompts allow on the extras overlay', () => {
    for (const prompt of vibePrompts) {
      assertAllow(overlay, prompt, 'overlay vibe');
    }
  });

  it('keeps generic creative-direction prompts allow on the extras overlay', () => {
    for (const prompt of directionPrompts) {
      assertAllow(overlay, prompt, 'overlay direction');
    }
  });

  it('keeps ordinary-English overlaps allow when they are objects or weather', () => {
    for (const prompt of objectPrompts) {
      assertAllow(overlay, prompt, 'overlay object');
    }
  });

  it('does not trip on near-miss substrings of new artist/work tokens', () => {
    for (const prompt of nearMissPrompts) {
      assertAllow(overlay, prompt, 'overlay near-miss');
    }
  });

  it('keeps one-piece-of-tape style overlaps allow on the overlay path', () => {
    // The shipped catalog already blocks the bare "One Piece" bigram; the
    // extras overlay (this file's scope) must not add its own trip here.
    assertAllow(overlay, 'one piece of tape on the desk', 'overlay one-piece');
    for (const prompt of overlayOnlyPrompts) {
      assertAllow(overlay, prompt, 'overlay-only near-miss');
    }
  });

  it('keeps the same innocent prompts allow on the default catalog path', () => {
    const prompts = [...vibePrompts, ...directionPrompts, ...objectPrompts, ...nearMissPrompts];
    for (const prompt of prompts) {
      assertAllow(full, prompt, 'full-path');
    }
  });

  it('still allows public-domain and invented wrapper strings', () => {
    assertAllow(inventedCensor(), 'Mary had a little lamb, little lamb, little lamb', 'invented PD');
    assertAllow(inventedCensor(), 'dreamy 80s synthwave, warm analog pads, melancholic jazz', 'invented vibe');
    assertAllow(inventedCensor(), 'make it sound "warm and foggy" tonight', 'invented short quote');
    assertAllow(full, 'Mary had a little lamb, little lamb, little lamb', 'full PD');
  });

  it('still blocks explicit BMG / Hot 100 title prompts', () => {
    const cases = [
      'make it sound like Sympathy for the Devil',
      'lyrics of 7 Rings vibe',
      'Anarchy in the UK guitar take',
      'the song Grenade on analog tape',
      'the song Kryptonite on analog tape',
      'Morning Dew arrangement, soft tape',
      'Rain on Me synth stab',
      'Sign of the Times piano sketch',
      'the Orbiter song demo',
      'the song Wonderwall on analog tape',
      'the song Boston on analog tape',
      'Boston song sketch, Stella Lefty vocal',
      'the song Dracula on analog tape',
      'Something to Lose piano sketch',
      'the song 9 to 5 on piano',
      'Steamboat Willie title card, warm grain',
      'Nintendo Switch bumper sting',
      'Switch 2 unboxing sting, warm grain',
      'Joy-Con controller close-up, product shot',
      'Nintendo Direct title sting',
      'Jolene vocal cover, soft tape',
      'the song Loser on analog tape',
      'Jaded song sketch, tired vocal',
      'the song Animal on analog tape',
      'Earrings song sketch, soft tape',
      'Cinderella song sketch, soft tape',
      'The Cure synth sketch, cold reverb',
      'What You Need song sketch, soft tape',
      'Oh Yeah song sketch, soft tape',
      'Dai Dai perreo bounce sketch',
      'PlayStation startup sting, warm grain',
      'PlayStation 5 boot sting',
      'PS5 unboxing sting, warm grain',
      'DualSense controller close-up, product shot',
      'Xbox Series X boot sting',
      'Barbie dreamhouse title sting',
      'Gundam hangar sting, warm grain',
      'One Piece title sting, warm grain',
      'Suno watermark sting, warm grain',
      'Udio bounce sketch',
      'LEGO brick close-up, product shot',
      'Labubu unboxing sting, warm grain',
      'Pop Mart blind-box unboxing sting',
      'AirPods product shot, white background',
      'iPhone product shot, studio light',
      'Warner Music Group title sting',
      'Warner Music logo sting',
      'Universal Music Group title sting',
      'Atlantic Records title sting',
      'BMG logo sting, warm grain',
      'Naruto title sting',
      'Bluey title sting, warm grain',
      'ChatGPT prompt sting, product shot',
      'Midjourney prompt sting, product shot',
      'Fender logo sting, product shot',
      'Cocomelon title sting',
      'FNAF title sting',
      'OpenAI title sting, product shot',
      'Instagram product shot, studio light',
      'Facebook title sting',
      'Prime Video title sting',
      'Gibson logo sting, product shot',
      'Stable Diffusion prompt sting, product shot',
      'DALL-E prompt sting, product shot',
      'Funko unboxing sting',
      'Mattel title sting',
      'Valorant lobby title sting',
      'Hulu title sting',
      'Crunchyroll title sting',
      'Reddit title sting',
      'Yamaha logo sting, product shot',
      'Ableton title sting',
      'Nerf logo sting, product shot',
      'Hasbro title sting',
      'Copilot logo sting, product shot',
      'Grok title sting',
      'ElevenLabs title sting',
      'CapCut edit sting, product shot',
      'Serato DJ sting, product shot',
      'Helldivers lobby title sting',
      'Palworld lobby title sting',
      'Wicked logo sting, product shot',
      'Steam logo sting, product shot',
      'Shein product shot, studio light',
      'Bose logo sting, product shot',
      'JBL product shot, studio light',
      'IKEA product shot, studio light',
      'Unity logo sting, product shot',
      'Perplexity logo sting, product shot',
      'DeepSeek prompt sting, product shot',
      'Pika logo sting, product shot',
      'Luma logo sting, product shot',
      'Shazam title sting, product shot',
      'Oppenheimer title card, warm grain',
      'Saltburn title card, warm grain',
      'Kindle logo sting, product shot',
      'Siri logo sting, product shot',
      'Android logo sting, product shot',
      'Gmail title sting, product shot',
      'Kling logo sting, product shot',
      'Veo logo sting, product shot',
      'DJI drone close-up, product shot',
      'Sonos speaker product shot, studio light',
      'Canva title sting, product shot',
      'Qwen prompt sting, product shot',
      'Backrooms logo sting, product shot',
      'Thunderbolts logo sting, product shot',
      'Wonka title card, warm grain',
      'Silksong title card, warm grain',
      'Mandalorian title card, warm grain',
      'Grogu title card, warm grain',
      'Airbnb logo sting, product shot',
      'DoorDash logo sting, product shot',
      'Shopify logo sting, product shot',
      'Etsy logo sting, product shot',
      'Figma logo sting, product shot',
      'Bandai logo sting, product shot',
      'Patreon logo sting, product shot',
      'Substack logo sting, product shot',
      'FIFA title sting, warm grain',
      'OnlyFans logo sting, product shot',
      'HeyGen logo sting, product shot',
      'Venmo logo sting, product shot',
      'Walmart logo sting, product shot',
      'Technics logo sting, product shot',
      'Chipotle logo sting, product shot',
      'Expedia logo sting, product shot',
      'Costco logo sting, product shot',
      'Instacart logo sting, product shot',
      'Descript logo sting, product shot',
      'Nutella logo sting, product shot',
      'Interscope logo sting, product shot',
      'Evangelion title sting, warm grain',
      'PUBG title sting, warm grain',
      'Smiski blind-box unboxing sting',
      'Korg logo sting, product shot',
      'Sennheiser logo sting, product shot',
      'Focusrite logo sting, product shot',
      'Pioneer DJ logo sting, product shot',
      'LTX logo sting, product shot',
      'Skims logo sting, product shot',
      'Rhode logo sting, product shot',
      'Motown logo sting, product shot',
      'Deltarune title sting, warm grain',
      'Undertale title sting, warm grain',
      'Dota 2 title sting, warm grain',
      'GTA 6 title sting, warm grain',
      'Castlevania title sting, warm grain',
      'Zootopia title card, warm grain',
      'Gemini prompt sting, product shot',
      'Manus prompt sting, product shot',
      'Ideogram prompt sting, product shot',
      'Akai title sting, product shot',
      'Crocs product shot, studio light',
      'FragPunk title sting, warm grain',
      'Uma Musume title sting, warm grain',
      'Dandy\'s World title sting, warm grain',
      'GQuuuuuuX title sting, warm grain',
      'Samsung product shot, studio light',
      'Synthesia prompt sting, product shot',
      'Teenage Engineering product shot, studio light',
      'RCA Records logo sting, product shot',
      'Stussy product shot, studio light',
      'Balenciaga product shot, studio light',
      'Krea prompt sting, product shot',
      'Megabonk title sting, warm grain',
      'Adopt Me title sting, warm grain',
      'Brookhaven title sting, warm grain',
      'Italian Brainrot title sting, warm grain',
      'Rekordbox title sting, warm grain',
      'Capitol Records title sting, warm grain',
      'Epic Records title sting, warm grain',
      'HYBE title sting, warm grain',
      'Viggle prompt sting, product shot',
      'Higgsfield prompt sting, product shot',
      'Corteiz product shot, studio light',
    ];
    for (const prompt of cases) {
      const result = overlay.check(prompt);
      assert.equal(result.verdict, 'block', `${JSON.stringify(prompt)} => ${result.verdict}`);
    }
  });

  it('still catches explicit titles and artists on the default catalog path', () => {
    assert.equal(full.check('make it sound like Sympathy for the Devil').verdict, 'block');
    assert.equal(full.check('Anarchy in the UK guitar take').verdict, 'block');
    assert.equal(full.check('the song Grenade on analog tape').verdict, 'block');
    assert.equal(full.check("The Go-Go's jangly guitar take").verdict, 'review');
    assert.equal(full.check('Motley Crue stacked chorus, analog bus').verdict, 'review');
  });

  it('still reviews explicit new artist prompts', () => {
    const cases = [
      "The Go-Go's jangly guitar take",
      'Go Gos arrangement with tape hiss',
      'Sex Pistols gang vocals on analog tape',
      'Motley Crue stacked chorus, analog bus',
      'Tems stacked chorus, analog bus',
      'Luke Combs bar-room guitar',
      'Sam Fender guitar take',
      'Judeline hook over warm pads',
      'rusowsky bounce on cheap speakers',
      'Dolly Parton choir stack, analog bus',
      'Vincent Mason guitar take',
      'Dominic Fike late-night keys',
      'Malcolm Todd soft tape vocal',
      'Koe Wetzel bar-room guitar',
      'Steve Lacy bass bounce sketch',
      'Shakira hook over warm pads',
      'Ty Dolla $ign late-night keys',
      'Ty Dolla Sign hook over warm pads',
      'sombr bedroom demo, soft tape',
      'Shaboozey bar-room guitar',
      'Djo bar-room guitar',
      'Peso Pluma hook over warm pads',
      'Feid perreo bounce sketch',
      'GloRilla hook over warm pads',
      'Latto bounce on cheap speakers',
      'Hozier hook over warm pads',
      'Jessie Murph hook over warm pads',
      'Mitski hook over warm pads',
      'Tucker Wetmore hook over warm pads',
      '4batz hook over warm pads',
      'Gabito Ballesteros hook over warm pads',
      'Billy Strings guitar take, flatpicking',
      'Sierra Ferrell hook over warm pads',
      '2hollis hook over warm pads',
      'Grupo Frontera hook over warm pads',
      'd4vd hook over warm pads',
      'Nettspend hook over warm pads',
      'Glaive hook over warm pads',
      'Midwxst hook over warm pads',
      'El Malilla hook over warm pads',
      'Quannnic hook over warm pads',
      'Shallipopi hook over warm pads',
      'BOYNEXTDOOR hook over warm pads',
      'QWER hook over warm pads',
      'Seyi Vibez hook over warm pads',
    ];
    for (const prompt of cases) {
      const result = overlay.check(prompt);
      assert.equal(result.verdict, 'review', `${JSON.stringify(prompt)} => ${result.verdict}`);
    }
  });
});
