import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import {
  createCensor,
  defaultBlocklist,
  flattenBlocklist,
  mergeBlocklists,
} from '../src/index.js';

describe('blocklist', () => {
  it('ships an extras overlay without lyric fields', () => {
    assert.equal(typeof defaultBlocklist.version, 'number');
    const blob = JSON.stringify(defaultBlocklist).toLowerCase();
    assert.equal(blob.includes('verse 1'), false);
    assert.equal(blob.includes('chorus:'), false);
    assert.equal(blob.includes('"lyrics"'), false);
  });

  it('merges grouped lists and extra entries', () => {
    const merged = mergeBlocklists(
      { artists: ['Ada'] },
      { works: ['River Glass'], entries: [{ term: 'Nox', kind: 'trademark' }] },
    );
    assert.deepEqual(merged.artists, ['Ada']);
    assert.deepEqual(merged.works, ['River Glass']);
    assert.equal(merged.entries.length, 1);
  });

  it('drops leading articles so The Beatles-style terms hit the short form', () => {
    const entries = flattenBlocklist({ artists: ['The Silver Finch'] });
    assert.ok(entries.some((entry) => entry.tokens.join(' ') === 'silver finch'));
  });

  it('matches aliases and accent-folded spellings', () => {
    const censor = createCensor({
      replaceBlocklist: true,
      blocklist: {
        artists: [{ term: 'Beyoncé', aliases: ['Beyonce'] }],
        franchises: [{ term: 'Pokemon', aliases: ['Pokémon'] }],
      },
    });
    assert.equal(censor.check('beyonce-like vocals').verdict, 'review');
    assert.equal(censor.check('a Pokémon overworld theme').verdict, 'block');
  });

  it('lets an allowlist override a colliding custom term', () => {
    const censor = createCensor({
      replaceBlocklist: true,
      blocklist: { artists: ['dreamy'] },
      allowlist: ['dreamy'],
    });
    assert.equal(censor.check('dreamy pads').verdict, 'allow');
  });

  it('matches new overlay identifiers from invented prompts only', () => {
    const censor = createCensor({ replaceCatalog: true });
    const cases = [
      ['a Marvin Gaye groove on cheap speakers', 'review'],
      ['Bonnie Tyler vocal air over pads', 'review'],
      ['Goo Goo Dolls arrangement with tape hiss', 'review'],
      ['James Brown horns and a tight snare', 'review'],
      ['Bon Jovi gang vocals on analog tape', 'review'],
      ['Jim Steinman piano and stacked choir', 'review'],
      ['Mark Ronson brass stabs, dusty cassette', 'review'],
      ['Earth Wind & Fire horns, late night mix', 'review'],
      ['Ella Langley fiddle and dry vocal', 'review'],
      ['Morgan Wallen bar-room guitar', 'review'],
      ['Olivia Dean soft tape vocal', 'review'],
      ['Tame Impala phaser and muted drums', 'review'],
      ['JENNIE hook over warm pads', 'review'],
      ['KATSEYE stacked chorus, analog bus', 'review'],
      ['Stella Lefty pedal-steel demo', 'review'],
      ['PARTYNEXTDOOR late-night keys', 'review'],
      ['KAROL G perreo bounce on cheap speakers', 'review'],
      ['The Kinks jangly guitar take', 'review'],
      ['Dio operatic vocal over analog tape', 'review'],
      ['make it sound like Choosin Texas', 'block'],
      ['I Knew It I Knew You demo take', 'block'],
      ['Been By Now arrangement, soft tape', 'block'],
      ['Hate That I Made You Love Me sketch', 'block'],
      ['I Cannot wait — I Can\'t Love You Anymore', 'block'],
      ['Man I Need demo with dry vocal', 'block'],
      ['So Easy To Fall in Love sketch', 'block'],
      ['Be Her arrangement on analog tape', 'block'],
      ['Risk It All guitar take', 'block'],
      ['I Just Might piano sketch', 'block'],
      ['drop dead song sketch, tape hiss', 'block'],
      ['stupid song demo take', 'block'],
      ['Midnight Sun pads and soft choir', 'block'],
      ['Hootie Frutti bounce sketch', 'block'],
      ['Janice STFU demo take', 'block'],
      ['Babydoll arrangement on cheap speakers', 'block'],
      ['McArthur collab sketch', 'block'],
      ['Ain\'t No Mountain High Enough sketch', 'block'],
      ['All I Want for Christmas Is You sketch', 'block'],
      ['Eye of the Tiger guitar take', 'block'],
      ['Here Comes Santa Claus sketch', 'block'],
      ['Living On a Prayer gang vocal', 'block'],
      ['Paper Rings guitar take', 'block'],
      ['Great Balls of Fire piano take', 'block'],
      ['Ramblin\' Man guitar take', 'block'],
      ['Cruel Summer synth stab', 'block'],
      ['Twist and Shout gang vocal', 'block'],
      ['California Gurls bounce sketch', 'block'],
      ['We Belong Together vocal air', 'block'],
      ['Scars to Your Beautiful sketch', 'block'],
      ['Redbone bass and tape hiss', 'block'],
      ['Total Eclipse of the Heart choir', 'block'],
      ['I Feel Good horn stab', 'block'],
      ['the song Iris on analog tape', 'block'],
      ['the song Lola, jangly guitar take', 'block'],
      ['Holy Diver operatic vocal', 'block'],
      ['Got My Mind Set On You sketch', 'block'],
      ['Lucasfilm title card, warm grain', 'block'],
      ['Hanna-Barbera title sting', 'block'],
      ['Cartoon Network bumper sting', 'block'],
      ['Minions title sting', 'block'],
      ['Shrek swamp title sting', 'block'],
      ['Homer Simpson couch sting', 'block'],
      ['Han Solo cockpit sting', 'block'],
      ['The Go-Go\'s jangly guitar take', 'review'],
      ['Go Gos arrangement with tape hiss', 'review'],
      ['Sex Pistols gang vocals on analog tape', 'review'],
      ['Motley Crue stacked chorus, analog bus', 'review'],
      ['Mötley Crüe guitar take', 'review'],
      ['Luke Combs bar-room guitar', 'review'],
      ['Lil Baby bounce on cheap speakers', 'review'],
      ['Yung Miami hook over warm pads', 'review'],
      ['Noah Kahan soft tape vocal', 'review'],
      ['Zara Larsson synth stab', 'review'],
      ['Tems stacked chorus, analog bus', 'review'],
      ['Mac Miller late-night keys', 'review'],
      ['Burna Boy bounce sketch', 'review'],
      ['Sam Fender guitar take', 'review'],
      ['make it sound like Sympathy for the Devil', 'block'],
      ['Sign of the Times piano sketch', 'block'],
      ['Our Lips Are Sealed guitar take', 'block'],
      ['lyrics of 7 Rings vibe', 'block'],
      ['Anarchy in the UK guitar take', 'block'],
      ['Anarchy in the U.K. sketch', 'block'],
      ['Rain on Me synth stab', 'block'],
      ['the song Grenade on analog tape', 'block'],
      ['You Can\'t Always Get What You Want sketch', 'block'],
      ['Beauty and a Beat bounce sketch', 'block'],
      ['Kickstart My Heart guitar take', 'block'],
      ['Desolation Row arrangement, tape hiss', 'block'],
      ['What a Wonderful World sketch', 'block'],
      ['the song Kryptonite on analog tape', 'block'],
      ['BbY WOW bounce sketch', 'block'],
      ['BBY WOW arrangement on cheap speakers', 'block'],
      ['Be By You demo take', 'block'],
      ['Dead Fresh bounce sketch', 'block'],
      ['Spend Dat arrangement on analog tape', 'block'],
      ['Bottom Of Your Boots guitar take', 'block'],
      ['Loving Life Again piano sketch', 'block'],
      ['the Orbiter song demo, pads and soft choir', 'block'],
      ['Morning Dew arrangement, soft tape', 'block'],
      ['Morning Dew (Donk) sketch', 'block'],
      ['Judeline hook over warm pads', 'review'],
      ['rusowsky bounce on cheap speakers', 'review'],
      ['Rusowsky perreo bounce, dusty cassette', 'review'],
      ['Dolly Parton choir stack, analog bus', 'review'],
      ['Vincent Mason guitar take', 'review'],
      ['the song Boston on analog tape', 'block'],
      ['Boston song sketch, Stella Lefty vocal', 'block'],
      ['the song Dracula on analog tape', 'block'],
      ['Something to Lose piano sketch', 'block'],
      ['the song 9 to 5 on piano', 'block'],
      ['Steamboat Willie title card, warm grain', 'block'],
      ['Nintendo Switch bumper sting', 'block'],
      ['Nintendo Switch 2 unboxing sting', 'block'],
      ['Switch 2 unboxing sting, warm grain', 'block'],
      ['Joy-Con controller close-up, product shot', 'block'],
      ['Joy Con 2 click foley, game trailer', 'block'],
      ['Nintendo Direct title sting', 'block'],
      ['Thor character title sting', 'block'],
      ['Deadpool wisecrack title sting', 'block'],
      ['Wolverine claw sting, cinematic brass', 'block'],
      ['Loki trickster title card, warm grain', 'block'],
      ['Thanos snap title sting', 'block'],
      ['Avengers assemble title sting', 'block'],
      ['Encanto house title sting', 'block'],
      ['Moana ocean title sting', 'block'],
      ['Coco soundtrack title sting', 'block'],
      ['Toy Story lamp title sting', 'block'],
      ['Inside Out console title sting', 'block'],
      ['Halo franchise title sting', 'block'],
      ['Roblox lobby title sting', 'block'],
      ['Elden Ring title sting', 'block'],
      ['God of War title sting', 'block'],
      ['The Last of Us title sting', 'block'],
      ['Spotify wrap sting, product shot', 'block'],
      ['HBO static title sting', 'block'],
      ['Shaboozey bar-room guitar', 'review'],
      ['Naruto title sting', 'block'],
      ['Bluey title sting, warm grain', 'block'],
      ['ChatGPT prompt sting, product shot', 'block'],
      ['Midjourney prompt sting, product shot', 'block'],
      ['Fender logo sting, product shot', 'block'],
      ['Dominic Fike late-night keys', 'review'],
      ['Malcolm Todd soft tape vocal', 'review'],
      ['Koe Wetzel bar-room guitar', 'review'],
      ['Steve Lacy bass bounce sketch', 'review'],
      ['Shakira hook over warm pads', 'review'],
      ['Ty Dolla $ign late-night keys', 'review'],
      ['Ty Dolla Sign hook over warm pads', 'review'],
      ['sombr bedroom demo, soft tape', 'review'],
      ['Jolene vocal cover, soft tape', 'block'],
      ['the song Loser on analog tape', 'block'],
      ['Jaded song sketch, tired vocal', 'block'],
      ['the song Animal on analog tape', 'block'],
      ['Earrings song sketch, soft tape', 'block'],
      ['Cinderella song sketch, soft tape', 'block'],
      ['The Cure synth sketch, cold reverb', 'block'],
      ['What You Need song sketch, soft tape', 'block'],
      ['Oh Yeah song sketch, soft tape', 'block'],
      ['Dai Dai perreo bounce sketch', 'block'],
      ['PlayStation startup sting, warm grain', 'block'],
      ['PlayStation 5 boot sting', 'block'],
      ['PS5 unboxing sting, warm grain', 'block'],
      ['DualSense controller close-up, product shot', 'block'],
      ['Xbox Series X boot sting', 'block'],
      ['Barbie dreamhouse title sting', 'block'],
      ['Gundam hangar sting, warm grain', 'block'],
      ['One Piece title sting, warm grain', 'block'],
      ['Suno watermark sting, warm grain', 'block'],
      ['Udio bounce sketch', 'block'],
      ['LEGO brick close-up, product shot', 'block'],
      ['Labubu unboxing sting, warm grain', 'block'],
      ['Pop Mart blind-box unboxing sting', 'block'],
      ['AirPods product shot, white background', 'block'],
      ['iPhone product shot, studio light', 'block'],
      ['Warner Music Group title sting', 'block'],
      ['Universal Music Group title sting', 'block'],
      ['Atlantic Records title sting', 'block'],
      ['BMG logo sting, warm grain', 'block'],
      ['Djo bar-room guitar', 'review'],
      ['Cocomelon title sting', 'block'],
      ['FNAF title sting', 'block'],
      ['OpenAI title sting, product shot', 'block'],
      ['Instagram product shot, studio light', 'block'],
      ['Facebook title sting', 'block'],
      ['Prime Video title sting', 'block'],
      ['Gibson logo sting, product shot', 'block'],
      ['Stable Diffusion prompt sting, product shot', 'block'],
      ['DALL-E prompt sting, product shot', 'block'],
      ['Funko unboxing sting', 'block'],
      ['Mattel title sting', 'block'],
      ['Peso Pluma hook over warm pads', 'review'],
      ['Valorant lobby title sting', 'block'],
      ['Hulu title sting', 'block'],
      ['Crunchyroll title sting', 'block'],
      ['Reddit title sting', 'block'],
      ['Yamaha logo sting, product shot', 'block'],
      ['Ableton title sting', 'block'],
      ['Nerf logo sting, product shot', 'block'],
      ['Hasbro title sting', 'block'],
      ['Copilot logo sting, product shot', 'block'],
      ['Grok title sting', 'block'],
      ['ElevenLabs title sting', 'block'],
      ['CapCut edit sting, product shot', 'block'],
      ['Serato DJ sting, product shot', 'block'],
      ['Feid perreo bounce sketch', 'review'],
      ['Helldivers lobby title sting', 'block'],
      ['Palworld lobby title sting', 'block'],
      ['Wicked logo sting, product shot', 'block'],
      ['Steam logo sting, product shot', 'block'],
      ['Shein product shot, studio light', 'block'],
      ['Bose logo sting, product shot', 'block'],
      ['JBL product shot, studio light', 'block'],
      ['IKEA product shot, studio light', 'block'],
      ['Unity logo sting, product shot', 'block'],
      ['Perplexity logo sting, product shot', 'block'],
      ['DeepSeek prompt sting, product shot', 'block'],
      ['Pika logo sting, product shot', 'block'],
      ['Luma logo sting, product shot', 'block'],
      ['Shazam title sting, product shot', 'block'],
      ['GloRilla hook over warm pads', 'review'],
      ['Latto bounce on cheap speakers', 'review'],
      ['Oppenheimer title card, warm grain', 'block'],
      ['Saltburn title card, warm grain', 'block'],
      ['Kindle logo sting, product shot', 'block'],
      ['Siri logo sting, product shot', 'block'],
      ['Android logo sting, product shot', 'block'],
      ['Gmail title sting, product shot', 'block'],
      ['Kling logo sting, product shot', 'block'],
      ['Veo logo sting, product shot', 'block'],
      ['DJI drone close-up, product shot', 'block'],
      ['Sonos speaker product shot, studio light', 'block'],
      ['Canva title sting, product shot', 'block'],
      ['Qwen prompt sting, product shot', 'block'],
      ['Hozier hook over warm pads', 'review'],
      ['Wonka title card, warm grain', 'block'],
      ['Backrooms logo sting, product shot', 'block'],
      ['Silksong title card, warm grain', 'block'],
      ['Thunderbolts logo sting, product shot', 'block'],
      ['Mandalorian title card, warm grain', 'block'],
      ['Grogu title card, warm grain', 'block'],
      ['Airbnb logo sting, product shot', 'block'],
      ['DoorDash logo sting, product shot', 'block'],
      ['Shopify logo sting, product shot', 'block'],
      ['Etsy logo sting, product shot', 'block'],
      ['Figma logo sting, product shot', 'block'],
      ['Bandai logo sting, product shot', 'block'],
      ['Patreon logo sting, product shot', 'block'],
      ['Substack logo sting, product shot', 'block'],
      ['Jessie Murph hook over warm pads', 'review'],
      ['FIFA title sting, warm grain', 'block'],
      ['OnlyFans logo sting, product shot', 'block'],
      ['HeyGen logo sting, product shot', 'block'],
      ['Venmo logo sting, product shot', 'block'],
      ['Walmart logo sting, product shot', 'block'],
      ['Technics logo sting, product shot', 'block'],
      ['Chipotle logo sting, product shot', 'block'],
      ['Expedia logo sting, product shot', 'block'],
      ['Costco logo sting, product shot', 'block'],
      ['Instacart logo sting, product shot', 'block'],
      ['Descript logo sting, product shot', 'block'],
      ['Nutella logo sting, product shot', 'block'],
      ['Interscope logo sting, product shot', 'block'],
      ['aespa hook over warm pads', 'review'],
      ['Sprunki title sting, warm grain', 'block'],
      ['Ne Zha title sting, warm grain', 'block'],
      ['Nezha 2 title sting, warm grain', 'block'],
      ['Shure mic close-up, product shot', 'block'],
      ['AKG headphone product shot, studio light', 'block'],
      ['Arturia synth product shot, studio light', 'block'],
      ['BandLab mix sting, product shot', 'block'],
      ['DistroKid release sting, product shot', 'block'],
      ['Elgato capture product shot, studio light', 'block'],
      ['close-up on the Rode logo, product shot', 'block'],
      ['Mitski hook over warm pads', 'review'],
      ['Tucker Wetmore hook over warm pads', 'review'],
      ['4batz hook over warm pads', 'review'],
      ['Gabito Ballesteros hook over warm pads', 'review'],
      ['Evangelion title sting, warm grain', 'block'],
      ['PUBG title sting, warm grain', 'block'],
      ['Smiski blind-box unboxing sting', 'block'],
      ['Korg logo sting, product shot', 'block'],
      ['Sennheiser logo sting, product shot', 'block'],
      ['Focusrite logo sting, product shot', 'block'],
      ['Pioneer DJ logo sting, product shot', 'block'],
      ['LTX logo sting, product shot', 'block'],
      ['Skims logo sting, product shot', 'block'],
      ['Rhode logo sting, product shot', 'block'],
      ['Motown logo sting, product shot', 'block'],
      ['Billy Strings guitar take, flatpicking', 'review'],
      ['Sierra Ferrell hook over warm pads', 'review'],
      ['2hollis hook over warm pads', 'review'],
      ['Grupo Frontera hook over warm pads', 'review'],
      ['Deltarune title sting, warm grain', 'block'],
      ['Undertale title sting, warm grain', 'block'],
      ['Dota 2 title sting, warm grain', 'block'],
      ['GTA 6 title sting, warm grain', 'block'],
      ['Castlevania title sting, warm grain', 'block'],
      ['Zootopia title card, warm grain', 'block'],
      ['Gemini prompt sting, product shot', 'block'],
      ['Manus prompt sting, product shot', 'block'],
      ['Ideogram prompt sting, product shot', 'block'],
      ['Akai title sting, product shot', 'block'],
      ['Crocs product shot, studio light', 'block'],
      ['d4vd hook over warm pads', 'review'],
      ['Nettspend hook over warm pads', 'review'],
      ['Glaive hook over warm pads', 'review'],
      ['Midwxst hook over warm pads', 'review'],
      ['El Malilla hook over warm pads', 'review'],
      ['FragPunk title sting, warm grain', 'block'],
      ['Uma Musume title sting, warm grain', 'block'],
      ['Dandy\'s World title sting, warm grain', 'block'],
      ['GQuuuuuuX title sting, warm grain', 'block'],
      ['Samsung product shot, studio light', 'block'],
      ['Synthesia prompt sting, product shot', 'block'],
      ['Teenage Engineering product shot, studio light', 'block'],
      ['RCA Records logo sting, product shot', 'block'],
      ['Stussy product shot, studio light', 'block'],
      ['a Stüssy lookbook page, product shot', 'block'],
      ['Balenciaga product shot, studio light', 'block'],
      ['Krea prompt sting, product shot', 'block'],
      ['Quannnic hook over warm pads', 'review'],
      ['Shallipopi hook over warm pads', 'review'],
      ['BOYNEXTDOOR hook over warm pads', 'review'],
      ['QWER hook over warm pads', 'review'],
      ['Seyi Vibez hook over warm pads', 'review'],
      ['Megabonk title sting, warm grain', 'block'],
      ['Adopt Me title sting, warm grain', 'block'],
      ['Brookhaven title sting, warm grain', 'block'],
      ['Italian Brainrot title sting, warm grain', 'block'],
      ['Rekordbox title sting, warm grain', 'block'],
      ['Capitol Records title sting, warm grain', 'block'],
      ['Epic Records title sting, warm grain', 'block'],
      ['HYBE title sting, warm grain', 'block'],
      ['Viggle prompt sting, product shot', 'block'],
      ['Higgsfield prompt sting, product shot', 'block'],
      ['Corteiz product shot, studio light', 'block'],
      ['DannyLux hook over warm pads', 'review'],
      ['Eslabon Armado hook over warm pads', 'review'],
      ['Nemzzz hook over warm pads', 'review'],
      ['Fireboy DML hook over warm pads', 'review'],
      ['P1Harmony hook over warm pads', 'review'],
      ['Piggy character title sting, warm grain', 'block'],
      ['Mickey 17 title sting, warm grain', 'block'],
      ['Bongo Cat title sting, warm grain', 'block'],
      ['PixVerse prompt sting, product shot', 'block'],
      ['Hailuo prompt sting, product shot', 'block'],
      ['MiniMax logo sting, product shot', 'block'],
      ['Whisk logo sting, product shot', 'block'],
      ['LANDR prompt sting, product shot', 'block'],
      ['Monstercat title sting, warm grain', 'block'],
      ['Alamo Records title sting, warm grain', 'block'],
      ['Keychron product shot, studio light', 'block'],
      ['Oasis hook over warm pads', 'review'],
      ['Future hook over warm pads', 'review'],
      ['Disclosure hook over warm pads', 'review'],
      ['Underscores hook over warm pads', 'review'],
      ['Femtanyl hook over warm pads', 'review'],
      ['Hades 2 title sting, warm grain', 'block'],
      ['Battlefield 6 lobby title sting, warm grain', 'block'],
      ['Hirono unboxing sting, warm grain', 'block'],
      ['Schedule 1 lobby title sting, warm grain', 'block'],
      ['Skullpanda unboxing sting, warm grain', 'block'],
      ['Dimoo unboxing sting, warm grain', 'block'],
      ['Vidu prompt sting, product shot', 'block'],
      ['ComfyUI prompt sting, product shot', 'block'],
      ['Behringer title sting, product shot', 'block'],
      ['BAPE product shot, studio light', 'block'],
      ['Elektron title sting, product shot', 'block'],
      ['2XKO title sting, warm grain', 'block'],
      ['played 2XKO last night', 'block'],
      ['played Saros last night', 'block'],
      ['new Saros gameplay, late-night session', 'block'],
      ['Monchhichi unboxing sting, warm grain', 'block'],
      ['unboxed Monchhichi yesterday', 'block'],
      ['Jellycat product shot, studio light', 'block'],
      ['bought Jellycat plush yesterday', 'block'],
      ['GPT-5 product shot, studio light', 'block'],
      ['asked GPT-5 yesterday', 'block'],
      ['GPT 5 product shot, studio light', 'block'],
      ['NotebookLM product shot, studio light', 'block'],
      ['used NotebookLM yesterday', 'block'],
      ['Hunyuan prompt sting, product shot', 'block'],
      ['rendered with Hunyuan yesterday', 'block'],
      ['Lovable logo sting, product shot', 'block'],
      ['built with Lovable yesterday', 'block'],
      ['Windsurf logo sting, product shot', 'block'],
      ['coded with Windsurf yesterday', 'block'],
      ['Replit prompt sting, product shot', 'block'],
      ['coded with Replit yesterday', 'block'],
      ['Captions logo sting, product shot', 'block'],
      ['edited with Captions yesterday', 'block'],
      ['Granola logo sting, product shot', 'block'],
      ['noted with Granola yesterday', 'block'],
      ['Kith logo sting, product shot', 'block'],
      ['wore Kith yesterday', 'block'],
      ['Jacquemus product shot, studio light', 'block'],
      ['wore Jacquemus yesterday', 'block'],
      ['Sp5der product shot, studio light', 'block'],
      ['wore Sp5der yesterday', 'block'],
      ['Hellstar product shot, studio light', 'block'],
      ['wore Hellstar yesterday', 'block'],
      ['Moliy hook over warm pads', 'review'],
      ['heard Moliy yesterday', 'review'],
      ['YTB Fatt hook over warm pads', 'review'],
      ['heard YTB Fatt yesterday', 'review'],
      ['Ghostemane hook over warm pads', 'review'],
      ['heard Ghostemane yesterday', 'review'],
      ['Clavish hook over warm pads', 'review'],
      ['heard Clavish yesterday', 'review'],
      ['Odeal hook over warm pads', 'review'],
      ['heard Odeal yesterday', 'review'],
      ['Mofusand character title sting, warm grain', 'block'],
      ['saw Mofusand yesterday', 'block'],
      ['Tralalero Tralala title sting, warm grain', 'block'],
      ['saw Tralalero Tralala yesterday', 'block'],
      ['Wuchang title sting, warm grain', 'block'],
      ['played Wuchang yesterday', 'block'],
      ['Kits AI prompt sting, product shot', 'block'],
      ['used Kits AI yesterday', 'block'],
      ['TuneCore logo sting, product shot', 'block'],
      ['released with TuneCore yesterday', 'block'],
      ['UnitedMasters logo sting, product shot', 'block'],
      ['released with UnitedMasters yesterday', 'block'],
      ['Squishmallows product shot, studio light', 'block'],
      ['hugged Squishmallows yesterday', 'block'],
      ['Insta360 product shot, studio light', 'block'],
      ['filmed with Insta360 yesterday', 'block'],
      ['Bitwig title sting, product shot', 'block'],
      ['produced with Bitwig yesterday', 'block'],
      ['Mubi title sting, warm grain', 'block'],
      ['watched Mubi yesterday', 'block'],
      ['Letterboxd title sting, warm grain', 'block'],
      ['logged on Letterboxd yesterday', 'block'],
      ['FattMack hook over warm pads', 'review'],
      ['heard FattMack yesterday', 'review'],
      ['Aldn hook over warm pads', 'review'],
      ['heard Aldn yesterday', 'review'],
      ['Lasmid hook over warm pads', 'review'],
      ['heard Lasmid yesterday', 'review'],
      ['XLOV hook over warm pads', 'review'],
      ['heard XLOV yesterday', 'review'],
      ['Kettama bounce on cheap speakers', 'review'],
      ['heard Kettama yesterday', 'review'],
      ['late-night REPO lobby, warm grain', 'block'],
      ['played REPO yesterday', 'block'],
      ['R.E.P.O. title sting, warm grain', 'block'],
      ['played R.E.P.O. yesterday', 'block'],
      ['Fisch title sting, warm grain', 'block'],
      ['played Fisch yesterday', 'block'],
      ['BedWars title sting, warm grain', 'block'],
      ['played BedWars yesterday', 'block'],
      ['Bed Wars title sting, warm grain', 'block'],
      ['played Bed Wars yesterday', 'block'],
      ['Takopi title sting, warm grain', 'block'],
      ['watched Takopi yesterday', 'block'],
      ['TDE logo sting, warm grain', 'block'],
      ['released with TDE yesterday', 'block'],
      ['Amuse logo sting, warm grain', 'block'],
      ['released with Amuse yesterday', 'block'],
      ['SeaArt prompt sting, product shot', 'block'],
      ['rendered with SeaArt yesterday', 'block'],
      ['FabFilter title sting, product shot', 'block'],
      ['mixed with FabFilter yesterday', 'block'],
      ['Beyerdynamic product shot, studio light', 'block'],
      ['tracked with Beyerdynamic yesterday', 'block'],
      ['Fujifilm product shot, studio light', 'block'],
      ['shot on Fujifilm yesterday', 'block'],
      ['shelf Glossier product, studio light', 'block'],
      ['used Glossier yesterday', 'block'],
      ['Floodlights hook over warm pads', 'review'],
      ['heard Floodlights yesterday', 'review'],
      ['PlaqueBoyMax hook over warm pads', 'review'],
      ['heard PlaqueBoyMax yesterday', 'review'],
      ['Tml Vibez hook over warm pads', 'review'],
      ['heard Tml Vibez yesterday', 'review'],
      ['Shoday hook over warm pads', 'review'],
      ['heard Shoday yesterday', 'review'],
      ['M Huncho hook over warm pads', 'review'],
      ['heard M Huncho yesterday', 'review'],
      ['Malugi bounce on cheap speakers', 'review'],
      ['heard Malugi yesterday', 'review'],
      ['Lafufu unboxing sting, warm grain', 'block'],
      ['unboxed Lafufu yesterday', 'block'],
      ['Boox product shot, studio light', 'block'],
      ['used Boox yesterday', 'block'],
      ['Owala product shot, studio light', 'block'],
      ['used Owala yesterday', 'block'],
      ['Hoka product shot, studio light', 'block'],
      ['wore Hoka yesterday', 'block'],
      ['UGG product shot, studio light', 'block'],
      ['wore UGG yesterday', 'block'],
      ['Salomon product shot, studio light', 'block'],
      ['wore Salomon yesterday', 'block'],
      ['Polymarket title sting, product shot', 'block'],
      ['used Polymarket yesterday', 'block'],
      ['Kalshi title sting, product shot', 'block'],
      ['used Kalshi yesterday', 'block'],
      ['Starlink product shot, studio light', 'block'],
      ['used Starlink yesterday', 'block'],
      ['Bogg Bag product shot, studio light', 'block'],
      ['used Bogg Bag yesterday', 'block'],
      ['Bakey hook over warm pads', 'review'],
      ['heard Bakey yesterday', 'review'],
      ['ifeye hook over warm pads', 'review'],
      ['heard ifeye yesterday', 'review'],
      ['Sprints hook over warm pads', 'review'],
      ['heard Sprints yesterday', 'review'],
      ['Gurriers hook over warm pads', 'review'],
      ['heard Gurriers yesterday', 'review'],
      ['Lanie Gardner hook over warm pads', 'review'],
      ['heard Lanie Gardner yesterday', 'review'],
      ['ABLUME hook over warm pads', 'review'],
      ['heard ABLUME yesterday', 'review'],
      ['1900Rugrat hook over warm pads', 'review'],
      ['heard 1900Rugrat yesterday', 'review'],
      ['F1 official title sting, warm grain', 'block'],
      ['the F1 soundtrack sting, warm grain', 'block'],
      ['Nightreign title sting, warm grain', 'block'],
      ['played Nightreign yesterday', 'block'],
      ['Hacipupu unboxing sting, warm grain', 'block'],
      ['unboxed Hacipupu yesterday', 'block'],
      ['Pucky unboxing sting, warm grain', 'block'],
      ['unboxed Pucky yesterday', 'block'],
      ['OP-1 product shot, studio light', 'block'],
      ['used OP-1 yesterday', 'block'],
      ['SoundCloud title sting, warm grain', 'block'],
      ['streamed with SoundCloud yesterday', 'block'],
      ['AWAL title sting, warm grain', 'block'],
      ['released with AWAL yesterday', 'block'],
      ['OpenArt prompt sting, product shot', 'block'],
      ['rendered with OpenArt yesterday', 'block'],
      ['Cursor logo sting, product shot', 'block'],
      ['coded with Cursor yesterday', 'block'],
      ['Yotei title sting, warm grain', 'block'],
      ['played Yotei yesterday', 'block'],
      ['Nioh 3 title sting, warm grain', 'block'],
      ['played Nioh 3 yesterday', 'block'],
      ['Pragmata title sting, warm grain', 'block'],
      ['played Pragmata yesterday', 'block'],
      ['Bandcamp title sting, warm grain', 'block'],
      ['released on Bandcamp yesterday', 'block'],
      ['Audiomack title sting, warm grain', 'block'],
      ['released on Audiomack yesterday', 'block'],
      ['Mixcloud title sting, warm grain', 'block'],
      ['streamed on Mixcloud yesterday', 'block'],
      ['Warner Records logo sting, product shot', 'block'],
      ['signed to Warner Records yesterday', 'block'],
      ['Kobalt logo sting, product shot', 'block'],
      ['published with Kobalt yesterday', 'block'],
      ['Antigravity logo sting, product shot', 'block'],
      ['coded with Antigravity yesterday', 'block'],
      ['Codex logo sting, product shot', 'block'],
      ['coded with Codex yesterday', 'block'],
      ['LMArena prompt sting, product shot', 'block'],
      ['ranked on LMArena yesterday', 'block'],
      ['Uniqlo product shot, studio light', 'block'],
      ['wore Uniqlo yesterday', 'block'],
      ['Lululemon product shot, studio light', 'block'],
      ['wore Lululemon yesterday', 'block'],
      ['Feastables product shot, studio light', 'block'],
      ['snacked on Feastables yesterday', 'block'],
      ['PredictIt logo sting, product shot', 'block'],
      ['bet on PredictIt yesterday', 'block'],
      ['SM7B mic close-up, product shot', 'block'],
      ['tracked with SM7B yesterday', 'block'],
      ['Freepik stock sting, product shot', 'block'],
      ['licensed on Freepik yesterday', 'block'],
      ['Miniso product shot, studio light', 'block'],
      ['shopped at Miniso yesterday', 'block'],
      ['Daiso product shot, studio light', 'block'],
      ['shopped at Daiso yesterday', 'block'],
      ['Muji product shot, studio light', 'block'],
      ['shopped at Muji yesterday', 'block'],
      ["Arc'teryx product shot, studio light", 'block'],
      ["wore Arc'teryx yesterday", 'block'],
      ['Arcteryx product shot, studio light', 'block'],
      ['wore Arcteryx yesterday', 'block'],
      ['Vuori product shot, studio light', 'block'],
      ['wore Vuori yesterday', 'block'],
      ['Rhude product shot, studio light', 'block'],
      ['wore Rhude yesterday', 'block'],
      ['Nocta product shot, studio light', 'block'],
      ['wore Nocta yesterday', 'block'],
      ['Hollister product shot, studio light', 'block'],
      ['wore Hollister yesterday', 'block'],
      ['Olipop product shot, studio light', 'block'],
      ['sipped Olipop yesterday', 'block'],
      ['OP-Z keys close-up, product shot', 'block'],
      ['tracked with OP-Z yesterday', 'block'],
      ['GoXLR mixer close-up, product shot', 'block'],
      ['streamed with GoXLR yesterday', 'block'],
      ['Kobo product shot, studio light', 'block'],
      ['read on Kobo yesterday', 'block'],
      ['Supernote product shot, studio light', 'block'],
      ['wrote on Supernote yesterday', 'block'],
      ['OnePlus product shot, studio light', 'block'],
      ['shot on OnePlus yesterday', 'block'],
      ['Xiaomi product shot, studio light', 'block'],
      ['shot on Xiaomi yesterday', 'block'],
      ['Anker product shot, studio light', 'block'],
      ['charged with Anker yesterday', 'block'],
      ['Pozer hook over warm pads', 'review'],
      ['heard Pozer yesterday', 'review'],
      ['Gyakie hook over warm pads', 'review'],
      ['heard Gyakie yesterday', 'review'],
      ['izna hook over warm pads', 'review'],
      ['heard izna yesterday', 'review'],
      ['Bayker Blankenship hook over warm pads', 'review'],
      ['heard Bayker Blankenship yesterday', 'review'],
      ['Happy Gilmore 2 title sting, warm grain', 'block'],
      ['watched Happy Gilmore 2 yesterday', 'block'],
      ['Lorcana title sting, warm grain', 'block'],
      ['played Lorcana yesterday', 'block'],
      ['Supabase logo sting, product shot', 'block'],
      ['built with Supabase yesterday', 'block'],
      ['Vercel logo sting, product shot', 'block'],
      ['deployed on Vercel yesterday', 'block'],
      ['Fal logo sting, product shot', 'block'],
      ['rendered with Fal yesterday', 'block'],
      ['DraftKings logo sting, product shot', 'block'],
      ['bet on DraftKings yesterday', 'block'],
      ['FanDuel logo sting, product shot', 'block'],
      ['bet on FanDuel yesterday', 'block'],
      ['Sephora product shot, studio light', 'block'],
      ['shopped at Sephora yesterday', 'block'],
      ['ate at Cava yesterday', 'block'],
      ['Cava logo sting, product shot', 'block'],
      ['wore Vans yesterday', 'block'],
      ['Vans logo sting, product shot', 'block'],
      ['wore Converse yesterday', 'block'],
      ['Converse logo sting, product shot', 'block'],
      ['Bearbrick unboxing sting, warm grain', 'block'],
      ['unboxed Bearbrick yesterday', 'block'],
    ];
    for (const [prompt, verdict] of cases) {
      const result = censor.check(prompt);
      assert.equal(result.verdict, verdict, `${JSON.stringify(prompt)} => ${result.verdict} (expected ${verdict})`);
    }
  });
});

